In [57]:
import numpy as np

motions = [(l.split()[0], int(l.split()[1])) for l in open(f"inputs/09-input.txt").read().splitlines()]

def inst_to_vec(inst):
    x,y = (0,0)
    if inst[0] in ["L", "R"]:
        x = inst[1] if inst[0] == "R" else -inst[1]
    if inst[0] in ["U", "D"]:
        y = inst[1] if inst[0] == "U" else -inst[1]
    return np.array([x,y])

vecs = [inst_to_vec(m) for m in motions]

s = np.array([0,0])
h = np.array([0,0])
t = np.array([0,0])
t_hist = set(tuple(t))

def move(m, h, t):
    l = abs(sum(m))
    uvec = m//l
    for i in range(1,l+1):
        h2 = h + uvec
        if np.any(abs(h2 - t) > 1):
            t = h
            t_hist.add(tuple(t))
        h = h2
    return h, t

for m in vecs:
    h, t = move(m,h,t)

len(t_hist)

6181

In [68]:
rope = [np.array([0,0])] * 10
t_hist = set(tuple(rope[-1]))

def move2(m, rope):
    l = abs(sum(m))
    uvec = m//l
    for i in range(1,l+1):
        for k in range(0,9):
            p1 = rope[k]
            p2 = p1 + uvec
            if np.any(abs(p2 - rope[k+1]) > 1):
                rope[k+1] = p1
            rope[k] = p2
        t_hist.add(tuple(rope[-1]))
    return rope

# for m in vecs:
#     rope = move2(m, rope)

len(t_hist)

1

In [69]:
rope


[array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0]),
 array([0, 0])]

In [55]:
len(t_hist)

6181

In [46]:
np.any(abs(np.array([0,2]) - np.array([0,0])) > 1)

True

In [32]:
abs(sum(np.array([-1,0])))

np.array([-1,0])//abs(sum(np.array([-1,0])))

array([-1,  0])

In [34]:
h,t

(array([0, 0]), array([0, 0]))

In [42]:
move(vecs[0], h, t)

(array([-1,  0]), array([0, 0]))

In [43]:
move(vecs[1], *move(vecs[0], h, t))

(array([1, 0]), array([0, 0]))

In [52]:
tuple(np.array([0,0]))

(0, 0)