# [Day 4: Giant Squid](https://adventofcode.com/2021/day/4)
## Part 1

In [25]:
# Read numbers from text file (stripping newline chars and converting to int)
data = [grp for grp in open("inputs/04-input.txt").read().split("\n\n")]

numbers = [int(n) for n in data[0].split(',')]

cards = [c.split('\n') for c in data[1:]]

[[[91, 5, 64, 81, 34],
  [15, 99, 31, 63, 65],
  [45, 39, 54, 93, 83],
  [51, 14, 23, 86, 32],
  [19, 22, 16, 13, 3]],
 [[20, 83, 38, 85, 70],
  [69, 12, 14, 26, 84],
  [19, 76, 45, 78, 99],
  [22, 80, 90, 33, 46],
  [75, 31, 21, 6, 28]],
 [[22, 52, 65, 75, 2],
  [91, 12, 45, 18, 94],
  [38, 66, 85, 39, 1],
  [24, 36, 55, 74, 3],
  [89, 14, 79, 99, 48]],
 [[19, 58, 95, 22, 6],
  [48, 28, 57, 30, 72],
  [12, 67, 15, 37, 18],
  [33, 1, 49, 90, 60],
  [35, 41, 47, 11, 84]],
 [[89, 27, 65, 68, 19],
  [38, 83, 21, 81, 91],
  [67, 61, 87, 30, 10],
  [36, 45, 66, 56, 4],
  [82, 71, 44, 96, 90]],
 [[29, 84, 40, 62, 92],
  [69, 39, 2, 1, 56],
  [6, 20, 27, 97, 54],
  [14, 28, 65, 52, 32],
  [31, 58, 36, 95, 8]],
 [[84, 46, 4, 15, 66],
  [28, 99, 17, 68, 37],
  [57, 6, 8, 64, 12],
  [18, 23, 24, 45, 34],
  [39, 55, 85, 5, 19]],
 [[56, 63, 13, 76, 35],
  [7, 94, 24, 23, 67],
  [60, 44, 12, 25, 71],
  [78, 19, 42, 87, 39],
  [2, 3, 69, 26, 22]],
 [[75, 43, 42, 45, 77],
  [57, 59, 88, 3, 49],
  [27

In [136]:
import numpy as np

# Read numbers from text file (stripping newline chars and converting to int)
data = open("inputs/04-input.txt").read().splitlines()

numbers = np.array([int(x) for x in data[0].split(',')])

cards = [np.array(' '.join(data[(6*i)+2:(6*i)+7]).split()).reshape(5,5) for i in range(0,len(data)//6)]

cards_list = [list(map(int,' '.join(data[(6*i)+2:(6*i)+7]).split())) for i in range(0,len(data)//6)]
cards_list

def bingo(numbers:list, card:list):
    setn = set(numbers)
    setc = set(card) 
    if len(setn & setc)>=5:
        matches = [n in numbers for n in card]
        sum_non_matches = sum(card[i] for i,val in enumerate(matches) if not val)
        # Any matching row?
        
        if any([all(matches[5*i:5*i+5]) for i in range(0,5)]):
            return (True, sum_non_matches)
        if any([all(matches[i::5]) for i in range(0,5)]):
            return (True, sum_non_matches)
        return False
    else:
        return False

for i in range(0,len(numbers)):
    for j in range(0,len(cards_list)):
        is_bingo = bingo(numbers[:i], cards_list[j])
        if is_bingo:
            print(i,j)
            print('Card: \n',np.array(cards_list[j]).reshape(5,5))
            print('Numbers: \n', numbers[:i])
            answer = is_bingo[1] * numbers[i-1]
            print(f'Sum non-matches ({is_bingo[1]}) x last number called ({numbers[i-1]}) = {answer}')

            break
    if is_bingo:
        break

33 84
Card: 
 [[64 65  6 86 53]
 [10 56  2 88 73]
 [11 62 37 84  1]
 [71 42 76 51 77]
 [41 83 19 14  4]]
Numbers: 
 [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71]
Sum non-matches (562) x last number called (71) = 39902


## Part 2

In [159]:
for i in range(len(numbers),0,-1):
    for j in range(0,len(cards_list)):
        is_bingo = bingo(numbers[:i], cards_list[j])
        if not is_bingo:
            print('Card: \n',np.array(cards_list[j]).reshape(5,5))
            print('Numbers: \n', numbers[:i])
            print(f'Sum non-matches ({bingo(numbers[:i+1], cards_list[j])[1]}) x last number called ({numbers[i]}) = {bingo(numbers[:i+1], cards_list[j])[1] * numbers[i]}')
            break
    if not is_bingo:
        break

84 45
Card: 
 [[78 56 29 50 32]
 [79 92 38 49 45]
 [70 80 76 86 64]
 [53 22 20 66 60]
 [77 25 84 93 88]]
Numbers: 
 [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71 34 58  5 52 22 39 57 17  2 26  0 10 72 19  3
 64 65 82 46 31 63 91 24 18 12  9 79 50 98 69  4 78 54 43 68 87  7 67 48
 28 89 94 53 85 81 49 88  6 96 29]
Sum non-matches (481) x last number called (56) = 26936


In [ ]:
for i in range(len(numbers),0,-1):
    for j in range(0,len(cards_list)):
        is_bingo = bingo(numbers[:i], cards_list[j])
        if not is_bingo:
            print('Card: \n',np.array(cards_list[j]).reshape(5,5))
            print('Numbers: \n', numbers[:i])
            print(f'Sum non-matches ({bingo(numbers[:i+1], cards_list[j])[1]}) x last number called ({numbers[i]}) = {bingo(numbers[:i+1], cards_list[j])[1] * numbers[i]}')
            break
    if not is_bingo:
        break

84 45
Card: 
 [[78 56 29 50 32]
 [79 92 38 49 45]
 [70 80 76 86 64]
 [53 22 20 66 60]
 [77 25 84 93 88]]
Numbers: 
 [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71 34 58  5 52 22 39 57 17  2 26  0 10 72 19  3
 64 65 82 46 31 63 91 24 18 12  9 79 50 98 69  4 78 54 43 68 87  7 67 48
 28 89 94 53 85 81 49 88  6 96 29]
Sum non-matches (481) x last number called (56) = 26936
