# [Day 5: Hydrothermal Venture](https://adventofcode.com/2021/day/5)
## Part 1

In [1]:
# Read numbers from text file (stripping newline chars and converting to int)
data = open("inputs/05-input.txt").read().splitlines()

import parse

parsed = []
for l in data:
        p = parse.parse('{x1:d},{y1:d} -> {x2:d},{y2:d}', l)
        parsed.append(((p['x1'], p['y1']), (p['x2'], p['y2'])))

parsed





[((242, 601), (242, 18)),
 ((938, 357), (938, 128)),
 ((920, 574), (750, 574)),
 ((804, 978), (804, 813)),
 ((955, 932), (68, 45)),
 ((232, 604), (232, 843)),
 ((69, 570), (467, 968)),
 ((355, 432), (611, 688)),
 ((945, 19), (700, 19)),
 ((904, 932), (904, 918)),
 ((455, 65), (516, 65)),
 ((571, 485), (588, 485)),
 ((717, 142), (217, 142)),
 ((377, 344), (66, 344)),
 ((510, 818), (132, 818)),
 ((848, 709), (848, 950)),
 ((785, 50), (785, 857)),
 ((23, 981), (971, 33)),
 ((938, 45), (938, 327)),
 ((212, 402), (601, 13)),
 ((749, 142), (651, 240)),
 ((94, 930), (22, 930)),
 ((436, 467), (820, 851)),
 ((544, 265), (458, 265)),
 ((517, 708), (517, 785)),
 ((957, 893), (957, 22)),
 ((684, 610), (526, 452)),
 ((713, 687), (526, 687)),
 ((220, 781), (988, 13)),
 ((12, 45), (912, 945)),
 ((854, 677), (646, 677)),
 ((382, 498), (382, 64)),
 ((676, 879), (148, 351)),
 ((809, 52), (336, 525)),
 ((959, 951), (41, 33)),
 ((943, 162), (132, 973)),
 ((897, 732), (897, 308)),
 ((21, 196), (702, 877)),

In [136]:
import numpy as np

# Read numbers from text file (stripping newline chars and converting to int)
data = open("inputs/04-input.txt").read().splitlines()

numbers = np.array([int(x) for x in data[0].split(',')])

cards = [np.array(' '.join(data[(6*i)+2:(6*i)+7]).split()).reshape(5,5) for i in range(0,len(data)//6)]

cards_list = [list(map(int,' '.join(data[(6*i)+2:(6*i)+7]).split())) for i in range(0,len(data)//6)]
cards_list

def bingo(numbers:list, card:list):
    setn = set(numbers)
    setc = set(card) 
    if len(setn & setc)>=5:
        matches = [n in numbers for n in card]
        sum_non_matches = sum(card[i] for i,val in enumerate(matches) if not val)
        # Any matching row?
        
        if any([all(matches[5*i:5*i+5]) for i in range(0,5)]):
            return (True, sum_non_matches)
        if any([all(matches[i::5]) for i in range(0,5)]):
            return (True, sum_non_matches)
        return False
    else:
        return False

for i in range(0,len(numbers)):
    for j in range(0,len(cards_list)):
        is_bingo = bingo(numbers[:i], cards_list[j])
        if is_bingo:
            print(i,j)
            print('Card: \n',np.array(cards_list[j]).reshape(5,5))
            print('Numbers: \n', numbers[:i])
            answer = is_bingo[1] * numbers[i-1]
            print(f'Sum non-matches ({is_bingo[1]}) x last number called ({numbers[i-1]}) = {answer}')

            break
    if is_bingo:
        break

33 84
Card: 
 [[64 65  6 86 53]
 [10 56  2 88 73]
 [11 62 37 84  1]
 [71 42 76 51 77]
 [41 83 19 14  4]]
Numbers: 
 [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71]
Sum non-matches (562) x last number called (71) = 39902


## Part 2

In [159]:
for i in range(len(numbers),0,-1):
    for j in range(0,len(cards_list)):
        is_bingo = bingo(numbers[:i], cards_list[j])
        if not is_bingo:
            print('Card: \n',np.array(cards_list[j]).reshape(5,5))
            print('Numbers: \n', numbers[:i])
            print(f'Sum non-matches ({bingo(numbers[:i+1], cards_list[j])[1]}) x last number called ({numbers[i]}) = {bingo(numbers[:i+1], cards_list[j])[1] * numbers[i]}')
            break
    if not is_bingo:
        break

84 45
Card: 
 [[78 56 29 50 32]
 [79 92 38 49 45]
 [70 80 76 86 64]
 [53 22 20 66 60]
 [77 25 84 93 88]]
Numbers: 
 [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71 34 58  5 52 22 39 57 17  2 26  0 10 72 19  3
 64 65 82 46 31 63 91 24 18 12  9 79 50 98 69  4 78 54 43 68 87  7 67 48
 28 89 94 53 85 81 49 88  6 96 29]
Sum non-matches (481) x last number called (56) = 26936


In [ ]:
for i in range(len(numbers),0,-1):
    for j in range(0,len(cards_list)):
        is_bingo = bingo(numbers[:i], cards_list[j])
        if not is_bingo:
            print('Card: \n',np.array(cards_list[j]).reshape(5,5))
            print('Numbers: \n', numbers[:i])
            print(f'Sum non-matches ({bingo(numbers[:i+1], cards_list[j])[1]}) x last number called ({numbers[i]}) = {bingo(numbers[:i+1], cards_list[j])[1] * numbers[i]}')
            break
    if not is_bingo:
        break

84 45
Card: 
 [[78 56 29 50 32]
 [79 92 38 49 45]
 [70 80 76 86 64]
 [53 22 20 66 60]
 [77 25 84 93 88]]
Numbers: 
 [73 42 95 35 13 40 99 92 33 30 83  1 36 93 59 90 55 25 77 44 37 62 41 47
 80 23 51 61 21 20 76  8 71 34 58  5 52 22 39 57 17  2 26  0 10 72 19  3
 64 65 82 46 31 63 91 24 18 12  9 79 50 98 69  4 78 54 43 68 87  7 67 48
 28 89 94 53 85 81 49 88  6 96 29]
Sum non-matches (481) x last number called (56) = 26936
